### ISSUE TITLE
Consider adding/clarifying license

### ISSUE THREAD

**Issue by follower** [gaslightgames/UE4_EOS_Plugin#1]
Hi,

If your intention is for other developers to use your plugin it would be helpful if the repository included a `LICENCE.txt` file or otherwise indicated the terms of use for your code in the README.

(My interest was in how portable the C++ interface/wrapper you created might be to other game engines.)

Thanks.

**Comment by fastlorisstudios** [comment]
I provided an update to the README, hopefully clarifying what you're after.
If it's helpful with seeing how to do "stuff" outside of Unreal, go for it!  :-)
All of the actual EOS bits comes from Epic's sample, just with some UE4 Macros and ability to access/change/check stuff through Blueprints.
