### ISSUE TITLE
Can't start packaged game with EOS enabled

### ISSUE THREAD

**Issue by HiIAmMoot** [gaslightgames/UE4_EOS_Plugin#10]
I do not know the cause. But this is what I get when I try and start my game with this plugin enabled. I haven't tried with Development or Shipping builds however.
![image](https://user-images.githubusercontent.com/13383284/62084451-a7e2c180-b259-11e9-9860-203fbf5cb7a1.png)

**Comment by fastlorisstudios** [comment]
I have this plugin in my current project, with both Development and Shipping builds.  The issue I've had is related to the packaged exe not being able to find the DLL.

Right now, I've been copying the DLL into the Win64 directory:
Shipping\WindowsNoEditor\<Project Name>\Binaries\Win64

Not the ideal (nor final) solution, as it results in multiple DLL locations.

**Comment by HiIAmMoot** [comment]
That's weird. The dll should be included with what I had added.

Do you know if this was a problem before these lines of code were removed from build.cs?

`string BaseDirectory = Path.GetFullPath(Path.Combine(ModuleDirectory, "..", "..", "Source", "ThirdParty", "EOSSDK"));	
        PublicIncludePaths.Add(Path.Combine(BaseDirectory, "Include"));`

**Comment by fastlorisstudios** [comment]
So the missing DLL thing _was_ an issue before... I've just updated all my other projects that I'm using the EOS Plugin, to this latest version, regenerated, recompiled, repackaged, made sure I don't have the DLL in two places and: everything's working great!

I'm packaging in Development and Shipping builds.
Were you packaging in Debug?  Can you double check with Development and Shipping?  Obviously _something's_ not right, just gotta narrow down which bit :-)

**Comment by fastlorisstudios** [comment]
I've not heard from you for a while and with things working fine in multiple projects of my own, when packaged - I'll close this for now.
