### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by T4lus** [gaslightgames/UE4_EOS_Plugin#13]
Hi I follow all step
- Copy SDK
- Generate VS project
- Build Solution

but the compilation failled with this error listing, like if the SDK isn't found 

`
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS/Public/Authentication/Authentication.h(44): error C2061: syntax error: identifier 'EOS_AccountId' 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS/Public/Authentication/Authentication.h(49): error C2535: 'FAccountId::FAccountId(void)': member function already defined or declared 
2> E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS/Public/Authentication/Authentication.h(44): note: see declaration of 'FAccountId::FAccountId' 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS/Public/Authentication/Authentication.h(73): error C2833: 'operator EOS_AccountId' is not a recognized operator or type 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS/Public/Authentication/Authentication.h(73): error C2059: syntax error: 'newline' 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS/Public/Authentication/Authentication.h(74): error C2334: unexpected token(s) preceding '{'; skipping apparent function body 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS/Public/Authentication/Authentication.h(92): error C3646: 'AccountId': unknown override specifier 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS/Public/Authentication/Authentication.h(92): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS/Public/Authentication/Authentication.h(45): error C2065: 'InAccountId': undeclared identifier 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS/Public/Authentication/Authentication.h(45): error C2614: 'FAccountId': illegal member initialization: 'AccountId' is not a base or member 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS/Public/Authentication/Authentication.h(57): error C2065: 'AccountId': undeclared identifier 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS/Public/Authentication/Authentication.h(57): error C2039: 'AccountId': is not a member of 'FAccountId' 
2> E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS/Public/Authentication/Authentication.h(37): note: see declaration of 'FAccountId' 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS/Public/Authentication/Authentication.h(157): error C2061: syntax error: identifier 'EOS_AccountId' 
2> [9/14] UE4Editor-EOSBasic.lib 
2> Creating library E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Intermediate\Build\Win64\UE4Editor\Development\EOSBasic\UE4Editor-EOSBasic.lib and object E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Intermediate\Build\Win64\UE4Editor\Development\EOSBasic\UE4Editor-EOSBasic.exp 
2> [10/14] Module.UEOS.cpp 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Public\Authentication\Authentication.h(44): error C2061: syntax error: identifier 'EOS_AccountId' 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Public\Authentication\Authentication.h(49): error C2535: 'FAccountId::FAccountId(void)': member function already defined or declared 
2> E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Public\Authentication\Authentication.h(44): note: see declaration of 'FAccountId::FAccountId' 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Public\Authentication\Authentication.h(73): error C2833: 'operator EOS_AccountId' is not a recognized operator or type 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Public\Authentication\Authentication.h(73): error C2059: syntax error: 'newline' 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Public\Authentication\Authentication.h(74): error C2334: unexpected token(s) preceding '{'; skipping apparent function body 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Public\Authentication\Authentication.h(92): error C3646: 'AccountId': unknown override specifier 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Public\Authentication\Authentication.h(92): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Public\Authentication\Authentication.h(45): error C2065: 'InAccountId': undeclared identifier 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Public\Authentication\Authentication.h(45): error C2614: 'FAccountId': illegal member initialization: 'AccountId' is not a base or member 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Public\Authentication\Authentication.h(57): error C2065: 'AccountId': undeclared identifier 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Public\Authentication\Authentication.h(57): error C2039: 'AccountId': is not a member of 'FAccountId' 
2> E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Public\Authentication\Authentication.h(37): note: see declaration of 'FAccountId' 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Public\Authentication\Authentication.h(157): error C2061: syntax error: identifier 'EOS_AccountId' 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Authentication\Authentication.cpp(88): error C2440: '=': cannot convert from 'FAccountId' to 'EOS_EpicAccountId' 
2> E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Authentication\Authentication.cpp(88): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Authentication\Authentication.cpp(105): error C2660: 'EOS_Auth_CopyUserAuthToken': function does not take 3 arguments 
2> E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\ThirdParty\EOSSDK\Include\eos_auth.h(83): note: see declaration of 'EOS_Auth_CopyUserAuthToken' 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Authentication\Authentication.cpp(114): error C2065: 'EOS_AccountId': undeclared identifier 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Authentication\Authentication.cpp(114): error C2146: syntax error: missing ')' before identifier 'InAccountId' 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Authentication\Authentication.cpp(115): error C2143: syntax error: missing ';' before '{' 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Authentication\Authentication.cpp(115): error C2447: '{': missing function header (old-style formal list?) 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Authentication\Authentication.cpp(127): error C2660: 'UEOSAuthentication::AccountIDToString': function does not take 1 arguments 
2> E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Public\Authentication\Authentication.h(157): note: see declaration of 'UEOSAuthentication::AccountIDToString' 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Authentication\Authentication.cpp(134): error C2679: binary '=': no operator found which takes a right-hand operand of type 'const EOS_EpicAccountId' (or there is no acceptable conversion) 
2> E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Public\Authentication\Authentication.h(53): note: could be 'FAccountId &FAccountId::operator =(const FAccountId &)' 
2> E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Authentication\Authentication.cpp(134): note: while trying to match the argument list '(FAccountId, const EOS_EpicAccountId)' 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Authentication\Authentication.cpp(140): error C2679: binary '=': no operator found which takes a right-hand operand of type 'EOS_EpicAccountId' (or there is no acceptable conversion) 
2> E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Public\Authentication\Authentication.h(53): note: could be 'FAccountId &FAccountId::operator =(const FAccountId &)' 
2> E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Authentication\Authentication.cpp(140): note: while trying to match the argument list '(FAccountId, EOS_EpicAccountId)' 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Authentication\Authentication.cpp(143): error C2664: 'EOS_ELoginStatus EOS_Auth_GetLoginStatus(EOS_HAuth,EOS_EpicAccountId)': cannot convert argument 2 from 'FAccountId' to 'EOS_EpicAccountId' 
2> E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Authentication\Authentication.cpp(143): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called 
2> E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\ThirdParty\EOSSDK\Include\eos_auth.h(67): note: see declaration of 'EOS_Auth_GetLoginStatus' 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Authentication\Authentication.cpp(190): error C2660: 'UEOSAuthentication::AccountIDToString': function does not take 1 arguments 
2> E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Public\Authentication\Authentication.h(157): note: see declaration of 'UEOSAuthentication::AccountIDToString' 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Authentication\Authentication.cpp(223): error C2065: 'EOS_ACCOUNTID_MAX_LENGTH': undeclared identifier 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Authentication\Authentication.cpp(225): error C2065: 'AccountId': undeclared identifier 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Authentication\Authentication.cpp(225): error C3861: 'EOS_AccountId_ToString': identifier not found 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Authentication\Authentication.cpp(232): error C2065: 'EOS_AccountId': undeclared identifier 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Authentication\Authentication.cpp(232): error C2146: syntax error: missing ';' before identifier 'Account' 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Authentication\Authentication.cpp(232): error C2065: 'Account': undeclared identifier 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Authentication\Authentication.cpp(232): error C3861: 'EOS_AccountId_FromString': identifier not found 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Authentication\Authentication.cpp(233): error C2065: 'Account': undeclared identifier 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Authentication\Authentication.cpp(238): error C2065: 'AccountId': undeclared identifier 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Authentication\Authentication.cpp(238): error C3861: 'EOS_AccountId_IsValid': identifier not found 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Friends\Friends.cpp(21): error C2440: '=': cannot convert from 'FAccountId' to 'EOS_EpicAccountId' 
2> E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Friends\Friends.cpp(21): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Friends\Friends.cpp(48): error C2440: '=': cannot convert from 'FAccountId' to 'EOS_EpicAccountId' 
2> E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Friends\Friends.cpp(48): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Friends\Friends.cpp(56): error C2440: '=': cannot convert from 'FAccountId' to 'EOS_EpicAccountId' 
2> E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Friends\Friends.cpp(56): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Friends\Friends.cpp(58): error C2065: 'EOS_AccountId': undeclared identifier 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Friends\Friends.cpp(58): error C2146: syntax error: missing ';' before identifier 'AccountId' 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Friends\Friends.cpp(58): error C2065: 'AccountId': undeclared identifier 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Friends\Friends.cpp(59): error C2065: 'AccountId': undeclared identifier 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Friends\Friends.cpp(66): error C2440: '=': cannot convert from 'FAccountId' to 'EOS_EpicAccountId' 
2> E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Friends\Friends.cpp(66): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Friends\Friends.cpp(67): error C2440: '=': cannot convert from 'FAccountId' to 'EOS_EpicAccountId' 
2> E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\Friends\Friends.cpp(67): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\UserInfo\UserInfo.cpp(21): error C2440: '=': cannot convert from 'FAccountId' to 'EOS_EpicAccountId' 
2> E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\UserInfo\UserInfo.cpp(21): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\UserInfo\UserInfo.cpp(22): error C2440: '=': cannot convert from 'const FAccountId' to 'EOS_EpicAccountId' 
2> E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\UserInfo\UserInfo.cpp(22): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\UserInfo\UserInfo.cpp(31): error C2440: '=': cannot convert from 'FAccountId' to 'EOS_EpicAccountId' 
2> E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\UserInfo\UserInfo.cpp(31): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\UserInfo\UserInfo.cpp(32): error C2440: '=': cannot convert from 'const FAccountId' to 'EOS_EpicAccountId' 
2> E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\UserInfo\UserInfo.cpp(32): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\UserInfo\UserInfo.cpp(65): error C2440: '<function-style-cast>': cannot convert from 'const EOS_EpicAccountId' to 'FAccountId' 
2> E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\UserInfo\UserInfo.cpp(65): note: No constructor could take the source type, or constructor overload resolution was ambiguous 
2>E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\UserInfo\UserInfo.cpp(73): error C2440: '<function-style-cast>': cannot convert from 'const EOS_EpicAccountId' to 'FAccountId' 
2> E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\UserInfo\UserInfo.cpp(73): note: No constructor could take the source type, or constructor overload resolution was ambiguous 
2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.MakeFile.Targets(41,5): error MSB3075: The command ""E:\Epic Games\UE_4.22\Engine\Build\BatchFiles\Build.bat" EOSBasicEditor Win64 Development -Project="E:\UE4\UE4_EOS_Plugin-master\EOSBasic\EOSBasic.uproject" -WaitMutex -FromMsBuild" exited with code 5. Please verify that you have sufficient rights to run this command. 
2>Done building project "EOSBasic.vcxproj" 
-- FAILED. 
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 1 skipped ==========`

**Comment by mbroderick** [comment]
I made a pull request that updates the plugin to work with the latest SDK, you should be able to apply those changes to your code to fix this issue. #14

**Comment by T4lus** [comment]
The Pull request solved the issue
but I can't Initialize EOS in the demoProject 

`Unhandled exception

EOSSDK_Win64_Shipping
UE4Editor_UEOS!UEOSManager::InitEOS() [E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Private\UEOSManager.cpp:106]
UE4Editor_UEOS!UEOSManager::execInitEOS() [E:\UE4\UE4_EOS_Plugin-master\EOSBasic\Plugins\UEOS\Source\UEOS\Public\UEOSManager.h:21]
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Core
UE4Editor_Core
UE4Editor_Core
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll`

**Comment by fastlorisstudios** [comment]
My apologies folks, for not getting this added to the repo' sooner!
I'll get this all fully checked over, committed and continue moving the Plugin forward, starting with my next slot of long-term available time, which will be this coming Friday (24/01/2020).

**Comment by fastlorisstudios** [comment]
Fixed in the latest push.
Updated everything to 4.24, updated the Plugin to the latest EOS SDK, fixed dependencies and added new values.

**Make sure to get your DeploymentID from your DevPortal and add it to the Config Options in the Editor!!!**
