### ISSUE TITLE
[4.24] EXCEPTION_ACCESS_VIOLATION Lastest Master

### ISSUE THREAD

**Issue by T4lus** [gaslightgames/UE4_EOS_Plugin#15]
Hi 
The sample crash on init 
I have set ProductID, SandboxID and DeployementID in the setting

```
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffff

UE4Editor_UEOS!UEOSManager::InitEOS() [E:\UE4\UE4_EOS_Plugin\EOSBasic\Plugins\UEOS\Source\UEOS\Private\UEOSManager.cpp:205]
UE4Editor_UEOS!UEOSManager::execInitEOS() [E:\UE4\UE4_EOS_Plugin\EOSBasic\Plugins\UEOS\Source\UEOS\Public\UEOSManager.h:21]
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Core
UE4Editor_Core
UE4Editor_Core
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll
```

**Comment by fastlorisstudios** [comment]
I can replicate, in Development Editor.
But when I cook and run using a DebugGame or even launch a DebugEditor - it works fine.

I think something is getting stripped by the Development build option. Will need to investigate further.

**Comment by cubehouse** [comment]
Using latest SDK (v. 1.4.1) I am getting this same crash in the sample project.

However, I've tried Dev Editor Standalone, Debug Editor Standalone, and Debug Packaged Build - none of these work for me :(
Read through the docs, but everything about the init looks good, and there is nothing more from the logs to give me a hint.

**Comment by fastlorisstudios** [comment]
> Using latest SDK (v. 1.4.1) I am getting this same crash in the sample project.
> 
> However, I've tried Dev Editor Standalone, Debug Editor Standalone, and Debug Packaged Build - none of these work for me :(
> Read through the docs, but everything about the init looks good, and there is nothing more from the logs to give me a hint.

Just did a quick check and I'd last updated the project prior to the release of 1.4.1, only having support up to 1.3. Will get the latest SDK and check what's going on with the Basic project :-)

**Comment by fastlorisstudios** [comment]
Updated to 1.4.1. Ran as a Standalone though either Editor and was able to replicate. Yet weirdly everything still ran when running a DebugGame from Visual Studio... go figure.

Anyway, the commit 1bbcc3b solves the issues I've seen my end, so _should_ sort it all for you, too :-)
