### ISSUE TITLE
Can't compile the UEOS plugin

### ISSUE THREAD

**Issue by AndrianV** [gaslightgames/UE4_EOS_Plugin#16]
Following the instructions on the README file:

> This plugin does not include the EOS (Epic Online Services) SDK. You will have to register and download this separately. Then copy the Bin, Include and Lib folders to the Plugins/Source/ThirdParty directory. Make sure to right click the .uproject, Generate Visual Studio files and compile.

The path to include the EOS SDK Bin, Include and Lib folders is actually mentioned in TXT file under:
"Plugins/UEOS/Source/ThirdParty/EOSSDK/AddSDKFoldersHere.txt"

I've done that and after generating Visual Studio files I tried to compile, using the UnrealHeaderTool included with the Binary installation of the 4.24 engine (I'm not using one built from source).

**I got this error:**
```
@progress 'Compiling C++ source code...' 73%
  [11/15] Module.UEOS.cpp
  E:/UE4_EOS_Plugin/EOSBasic/Plugins/UEOS/Source/UEOS/Private/UEOSManager.cpp(538): error C2838: 'EOS_Auth_DeviceAuth_AccountNotActive': illegal qualified name in member declaration
  E:/UE4_EOS_Plugin/EOSBasic/Plugins/UEOS/Source/UEOS/Private/UEOSManager.cpp(538): error C2065: 'EOS_Auth_DeviceAuth_AccountNotActive': undeclared identifier
  E:/UE4_EOS_Plugin/EOSBasic/Plugins/UEOS/Source/UEOS/Private/UEOSManager.cpp(540): error C2838: 'EOS_Auth_DeviceAuth_InvalidInfo': illegal qualified name in member declaration
  E:/UE4_EOS_Plugin/EOSBasic/Plugins/UEOS/Source/UEOS/Private/UEOSManager.cpp(540): error C2065: 'EOS_Auth_DeviceAuth_InvalidInfo': undeclared identifier
  E:/UE4_EOS_Plugin/EOSBasic/Plugins/UEOS/Source/UEOS/Private/UEOSManager.cpp(538): error C2051: case expression not constant
  E:/UE4_EOS_Plugin/EOSBasic/Plugins/UEOS/Source/UEOS/Private/UEOSManager.cpp(540): error C2051: case expression not constant
LogInit: Warning: Still incompatible or missing module: EOSBasic
LogInit: Warning: Still incompatible or missing module: UEOS
LogCore: Engine exit requested (reason: EngineExit() was called)
LogExit: Preparing to exit.
```

**Comment by fastlorisstudios** [comment]
Looks like you're using SDK v1.5 - which the project had not (yet) been updated to support.
Updated my local copy, replicated, fixed and pushed all here 02a3906
Also updated the ReadMe to fix the path/location and show the currently supported SDK version.
