### ISSUE TITLE
Hey - first time submitting a pull request for another project, have a correction.

### ISSUE THREAD

**Issue by MikhailSorokin** [gaslightgames/UE4_EOS_Plugin#18]
Could you add this in line 123 of UEOSCommon

`	case EOS_EResult::EOS_MissingParameters_DEPRECATED:`

Thanks for doing this, may have some updates with authentication in the next couple of days as well!

https://github.com/gaslightgames/UE4_EOS_Plugin/blob/bd8cf2b482962f659dc31eefb1d71162fcf655c3/EOSBasic/Plugins/UEOS/Source/UEOS/Public/UEOSCommon.cpp#L123

**Comment by fastlorisstudios** [comment]
Thanks for sending this over - I spotted this about an hour ago :-)
Fixed, pushed and made some changes, moved a few things around and am working on some parts.
