### ISSUE TITLE
Login not working!

### ISSUE THREAD

**Issue by saurabhguptarock** [gaslightgames/UE4_EOS_Plugin#19]
I have followed all steps that are written in readme file but still login fails.
Please add more clear error reasons

**Comment by fastlorisstudios** [comment]
I can only add/reply with login information that the SDK returns to me - I think there might be _some_ more appropriate reasons that we _can_ return. But for now, the basic reasons are/will be:

- Have you added your project on EAS (Epic Account Services)?
- Have you created a "Client" for your project?
- Did you get and add both the ClientId and Client Secret, to the project settings?
- I tested by launching the Auth Tool, so have you extracted that? Launched it? Created a login? And set the node in the Player Controller to "localhost:Port" where "Port" is the one you specified when starting the Auth Tool? And did you put the "name" in as the Name you added to the Auth Tool?

If you did all of those above _then_ it should work. If you've skipped or missed a step at all, then it wont work. Still very much a work in progress, so will get to adding more appropriate logging and feedback.

**Comment by lemontmoon** [comment]
I can confirm that login in works,, In new SDK 1.6 , there is one more login type i temporarily rewriten in EOS code as I am not working with github branches yet. You have to enter there 5 types of secret Tokens.  
1.ID of game 
2. sandbox ID
3.deployment ID
4.Client ID
5.Client Secret Key.
Then you can login with DevAuth tool or use Epics Login.
with dev auth tool ,, if you run it enter port 7777,, login to epic and create Credential Name
                              ,, keep devAuth running 
in login details in PlayerController  put localhost:7777 & CredentialName you have just created.

Run Eos with keyboard shortcut
Press "I"  to login

**Comment by fastlorisstudios** [comment]
Much appreciated @lemontmoon 😄 

If you are able to Initialise EOS within the basic application, then you already have the Product, Sandbox and Deployment IDs, so be sure to check that ClientId and Secret are in there.

Also, you can enter any port for initializing the Dev Auth tool - I often use 12345 (5 digit ports tend to work better on certain firewalls).

Loads more changes, result feedback and updates to come, but for now (having another confirm this works), I'll close this issue.

**Comment by lemontmoon** [comment]
Hi gaslightgames,,, 
I would like to ask you if you did sucessfuly tryed Social Overlay
It should work with Shift+F3 & It will alarm you with side screen popup that you have social overlay ready.
I've read in SDK that EOS need to be initialized before Direct3D to initialize Soc.Overlay in Unreal Engine. Is there need to rewrite your module to be initialized on for example PreConfig module loading phase or will it run without that ?

Social Overlay is already integrated and can be found in Launcher directory & is working perfect with SDK examples

When I've tryed it with SDK and initialized EOS after winmain, it was not launching Soc.Overlay

Thanks,

**Comment by lemontmoon** [comment]
When I've tryed it with SDK and initialized EOS after winmain, it was not launching Soc.Overlay
