### ISSUE TITLE
Social Overlay Qestion

### ISSUE THREAD

**Issue by lemontmoon** [gaslightgames/UE4_EOS_Plugin#20]
Hi gaslightgames,,,
I would like to ask you if you did sucessfuly tryed Social Overlay
 It should alarm you with side screen popup if you have social overlay initialized &  ready & you can press Shift+F3 to open it.
I've read in SDK that EOS need to be initialized before Direct3D to initialize Soc.Overlay in Unreal Engine. Is there need to rewrite your module to be initialized on for example PreConfig module loading phase or will it run without that ?

Social Overlay is already integrated and can be found in Launcher directory & is working perfect with SDK examples

When I've tryed it with SDK and initialized EOS after winmain, it was not launching Soc.Overlay

Thanks,

**Comment by fastlorisstudios** [comment]
It's on my list, and yeah, will need to rethink how things are initialized (whether automatically via the Plugin Init methods, or bound in some other way).

The overlay is lower on my priority list, as the Auth and User elements were/are required before you can access almost _any_ other part of the SDK, such as achievements or player storage.

**Comment by fastlorisstudios** [comment]
OK, so I had a spare bit of time to take a look 😄 

I've ammended the .uplugin's Load Type to "EarlyAsPossible," to try and get the Module to start-up before DX. I've also reworked the Startup method in the Module (so it's a bit cleaner) to check if we're in the Editor and if **not,** then try and Init EOS immediately. I've only tested in Standalone from the Editor to check that the standard stuff works - overlay _should/hopefully/might_ start working in a Packaged build.
To be clear - I've not tested the Overlay in any of the Editor launched approaches as, in theory, they should still NOT work. But this ought to work in a Packaged build and/or be a jumping off point to get the Overlay to work in Standalone.

**Comment by lemontmoon** [comment]
Hi, 
I have just did one test and Overlay is showing to me perfectly, but In Editor it causes Graphics problems,,, so you have to use overlay only in non editor state.
if (WITH_EDITOR) {
		PlatformOptions.Flags = EOS_PF_LOADING_IN_EDITOR;
	}
	else {
		PlatformOptions.Flags = 0;
	}
}
Also another very important thing is that you need to InitPlatform immediately on module startup, I made static PlatformHandle in EOSModule, then pass that handle to EOSManager on creation. Checked if PlatformHandle is valid & set bEOSInitialized = true . In my case I had to use PostConfigInit loading phase, so users will have to set thoose sandbox IDS etc in c++ code or somehow read from config.ini files.

FUEOSModule::InitPlatform(){
........
}
UEOSManager::UEOSManager()
	: PlatformHandle( NULL )
	, bEOSInitialized( false )
	, bEOSShutdown( false )
	, Authentication( nullptr )
	, Metrics( nullptr )
	, Friends( nullptr )
	, UserInfo( nullptr )
{
	PlatformHandle = FUEOSModule::GetPlatformHandle();
	if (PlatformHandle) {
		bEOSInitialized = true;
	}
}

**Comment by lemontmoon** [comment]
sorry it was PostConfigInit Loading Phase.
You can read about that here -> https://dev.epicgames.com/docs/services/en-US/Overlay/index.html
In that case, you dont have to init EOS via blueprints,,, it should be loaded before any Graphics hooks to the system. 
   PostConfigInit "typically where engine is loading or preparing shaders" - thats why overlay will not work after that phase because it is part of renderer & probably compiles its own shader. 
         SplashScreen  "means graphics and renderer has been hooked and tested first image"

**Comment by fastlorisstudios** [comment]
I'm moving this over to an OSS, akin to the Steam approach. So we'll no longer have our own config (add things to the DefaultEngine.ini, like the Steam plugin) and the loading phase will be moved to PreDefault (again, like the Steam one).
Gonna take me a few days to make this transition - but after that, we should be good :-)
