### ISSUE TITLE
EOS Plugin as Online Subsystem?

### ISSUE THREAD

**Issue by fastlorisstudios** [gaslightgames/UE4_EOS_Plugin#21]
I've been considering this for a while now, but I'm still not convinced.

On the one hand, we would have all the features from EOS available as an Online Subsystem (OSS) within UE4, much like Steam and many others.
And whilst you _can_ have multiple OSS' running at the same time (see loads of details about running Steam and Facebook at the same time, for example), [these docs](https://docs.unrealengine.com/en-US/Programming/Online/index.html) say:

> During initialization, the Online Subsystem will try to load the default online service module specified in the "Engine.ini" file. All access to an online service will go through this module.

Citing this as an example:
`[OnlineSubsystem]
DefaultPlatformService=<Default Platform Identifier>`

Now, here is my question/concern.
If we go the OSS route, I can see times when one would need to specify a _different_ OSS as the Default, such as console. And yes, we can query for the EOS OSS at any time, it wouldn't (however) be initialized _before_ the Rendering API had started (DirectX, for example), so the EOS overlay or any elements like this, would likely not work.
So keeping the EOS Plugin as its own entity, we can control the initialization and it's entirely separate from the OSS mechanism, so one could have both Steam (initialized as the Detault) _and_ EOS running, with the latter starting up entirely through this Plugin.

In classic adventure game style: do we go Left (OSS) or Right (separate)?

**Comment by sswires** [comment]
This plugin should be implemented using the OSS abstraction. Many developers will use a different default OSS depending on the store or (non-PC) platform.

If you take a look at the Steam OSS, it does have extensions available in the FOnlineSubsystemSteam implementation that gives you access to features not covered by the engine interfaces, such as encrypted app tickets.

If the plugin is enabled, then FOnlineSubsystemName::Init() should be called before the game even renders a frame.

**Comment by Zod20** [comment]
Given that EOS is in the same category alongside PSN, Xbox, Steam and directly replaces each of these subsystems on the respective platforms, it should be a OSS like the others.

**Comment by fastlorisstudios** [comment]
After I posted this, I had a middle-of-the-night realisation, so this is going to be switched over to an OSS, but I also need to clarify a few things.

1. The issue raised in my question is that because you can only have ONE OSS set by default, would the actual OSS portion get init'd if _not_ the default?
2. On consoles, my understanding is that one would need the PSN/XBL/etc OSS as the default and then could use EOS as a supplementary. Certainly how we've got UE4 games through cert in the past.
3. FOnlineSubsystemName::Init() isn't called by "default" but rather, manually. So it's not like "drop the Plugin is an an OSS and we're away." However, like in the Steam OSS, it's called in the Module start-up which _is_ called automagically, so in essence, what I've said is both correct and misleading.
4. Further to consoles doubling up the OSS, I can see times when on a desktop, one might want _both_ Steam and EOS, rather than a replacement. It's only in this instance (doubling OSS'), and with the docs saying only one gets initialized, that I was concerned.

All the other elements, such as how EOS is akin to the abstractions in OSS, is exactly _why_ I'm making the jump over to this approach. But it's all the _**other**_ stuff that is why I posed the question. The other bits are the elements that need(ed) answering - which I'm pretty confident I have the answers I need, now.
