### ISSUE TITLE
Plugin UEOS failed to load module not found

### ISSUE THREAD

**Issue by Blastertoad** [gaslightgames/UE4_EOS_Plugin#23]
I have cloned the repo, and freshly downloaded SDK 1.6 (EOS-SDK-13289764-v1.6) from Epic and copied Bin, Lib and Include folders to UE4_EOS_Plugin\EOSBasic\Plugins\UEOS\Source\ThirdParty\EOSSDK

Regardless of how many times I build vs files, or whether I am trying the plugin with sample project or a fresh 4.25 project I get the same message. "Plugin 'UEOS' failed to load because module 'UEOS' could not be found. Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project."

**Comment by fastlorisstudios** [comment]
Daft question but, did you compile the project in VS after generating the files?

Also, this whole current project will be deprecated in a matter of days, as everything will be switching over to an Online Subsystem approach.

**Comment by Blastertoad** [comment]
I have now compiled the project after sifting through the forum posts. As this project will no doubt be popular with devs only familiar in blueprint I would suggest adding an additional line to the readme instructing users to open the .sln and manually build it in VS. Also a link to the forum at the top of the readme would be a good idea since the git project comes up first in search results.
