### ISSUE TITLE
Project not working with new EOS Plugin

### ISSUE THREAD

**Issue by MikeOrthoshop** [gaslightgames/UE4_EOS_Plugin#26]
In the previous version before the OSS I was able to connect to my dev tool. I downloaded the OSS version and now I just get a black screen when I run the EOSBasic project. I have followed all the steps I believe (generated files, compiled, and added my ProductId, SandboxId, DeploymentId, ClientId and Client Secret to DefaultEngine.ini. I changed the ID, Token, and Type in the Request login blueprint as well. Not sure what I'm missing, but I can't get anything to even print to the screen when running as standalone.

**Comment by shukenmg** [comment]
You need to play in standalone mode.
Make sure everything is set correctly then try unblocking the Dev Auth tool in windows firewall for Private and Public connections.

It seems to be a bug where the Subsystem is loaded when you first open the project thus causing the editor to be unable to load the Subsystem then you play in the editor.

**Comment by fastlorisstudios** [comment]
There's (currenty) no UI, unlike the old version - as the events that triggered changes no longer exist. Check the logs for "Online Subsystem" and "EOS" and you'll see all the various states being printed.

If you PIE (even with Steam) it wont work. You'll _always_ need to play Standalone.
