### ISSUE TITLE
Can you add an MIT license file or similar

### ISSUE THREAD

**Issue by jimsimonz** [gaslightgames/UE4_EOS_Plugin#30]
I know it says in the description 'as is' but it'd be great if you could add one of the boilerplate licenses such as the MIT one from github. 

Awesome that you've added this, a bit perplexed as to why Epic haven't done an OSS for their own services!

**Comment by fastlorisstudios** [comment]
Right now, it's literally "as is" and do what you will. At this stage, a license change isn't on my radar.
