### ISSUE TITLE
State of the project? 

### ISSUE THREAD

**Issue by decryptedchaos** [gaslightgames/UE4_EOS_Plugin#31]
I have integrated your project into mine,  and I have been reading through the roadmap,   That said it appears this project isn't super far along,  only basic auth support.  

So my question is,  when do you expect this project to fully support EOS  (in my case: Session, Playerdata, and stats)? 

I'm nowhere near a finished project,  but I would like some assurances that this won't get abandoned in a few months and I have to rework my plan.

**Comment by fastlorisstudios** [comment]
After switching from the previous approach to the UE4 OSS approach, much of what _was_ implemented has yet to be brought over. The Session Interface is the big one, which is being worked on. The project is in no way going to be abandoned, but don't forget: Free, open source, part time. Not a full time project. Not someone being paid for it. So no, I wont give any assurances.
