### ISSUE TITLE
Broken/Bugged Out Interface

### ISSUE THREAD

**Issue by Sessional** [gaslightgames/UE4_EOS_Plugin#32]
I was attempting to move the plugin to my own project when I realized all of a sudden my UI had stopped working correctly. It appears that any right-click context menu has difficulties rendering after adding this plugin. Not only does the menu appear like this, in the case of blueprint where you are typing to find the node you want, it never fully redraws the menu and makes the menu completely unusable.

![image](https://user-images.githubusercontent.com/812920/87876544-59649080-c99e-11ea-8d1d-5d97e0d8aee4.png)

**Comment by fastlorisstudios** [comment]
Not had it completely unusable - on my machine, (when) this occurs, it sort of "pops" and refreshes back.

BUT, it's obviously an issue and I think it's in the EOS SDK DirectX API hooks. Scouring through the Steam OSS version to see if any IF_EDITOR (or equivalent) checks are performed before doing the bind.

**Comment by fastlorisstudios** [comment]
Fixed in 1ec77381ae5595491d62fd9c74ca9ff9e83cf411
