### ISSUE TITLE
A Bit Confused

### ISSUE THREAD

**Issue by Budgo** [gaslightgames/UE4_EOS_Plugin#34]
Hello!

I have recently downloaded the plugin, and I've been working over the past couple of days to make it work, but now I have a little problem. When I go into Visual Studio and attempt to Rebuild the program, I always seem to be doing well, and then I get these errors:
![image](https://user-images.githubusercontent.com/43380405/88307446-f2b2e000-ccd9-11ea-80dc-fb812c18cee7.png)
![image](https://user-images.githubusercontent.com/43380405/88307668-3c032f80-ccda-11ea-9aed-327530cd181f.png)

I also get these two warnings:
![image](https://user-images.githubusercontent.com/43380405/88307533-10804500-ccda-11ea-8953-fd38de8d6276.png)
![image](https://user-images.githubusercontent.com/43380405/88307591-2261e800-ccda-11ea-8290-17b252c0cd5c.png)
However I do have these files and directories. Any solutions?

**Comment by fastlorisstudios** [comment]
It looks like you've not got a folder for the Plugin.
In your cast, the Windows Explorer bar ought to read:
PC > Documents > Unreal Projects > UE4 EOS > Plugins > **OnlineSubsystemEOS** > Source > ThirdParty > EOSSDK

![FolderLog](https://user-images.githubusercontent.com/2463732/88311354-b2b72180-cd08-11ea-884e-7a1fc72055f6.png)

Also, be careful with putting your projects in something like the Windows Documents folder, as you might hit the folder and/or filename character limit when packaging your project!

**Comment by Budgo** [comment]
Guess I put it in the wrong place 😝 
![image](https://user-images.githubusercontent.com/43380405/88312205-d9149700-ccdf-11ea-9bde-dffa8581cf9d.png)

**Comment by Budgo** [comment]
![image](https://user-images.githubusercontent.com/43380405/88313855-1a0dab00-cce2-11ea-87d9-494d7cb636f9.png)
Oh no... another day another error. I'm not sure anything with this one though. I think it has something to do with a missing file(?).

**Comment by fastlorisstudios** [comment]
I still think there's something awry with your folder structure. Is this your own project or the EOS Basic sample project?

If the former (your own), double check your Plugins folder against the Basic project... if EOS Basic is working on its own, then try copying the Plugins folder from Basic into your own projects root (where your .uproject file lives).

**Comment by Budgo** [comment]
I'm trying to get the EOS Basic to work. My structure looks something like this:

```
Unreal Projects ┐
               UE4 EOS ┐
                                .vs
                                Binaries
                                Config
                                Content
                                DerivedDataCache
                                Intermediate
                                Plugins ┐
                                          Online SubsystemEOS
                                          Samples
                                          SDK
                                          ThirdPartyNotices
                                          
                                Saved
                                Source
                                EOSBasic.sln
                                EOSBasic.uproject
```

**Comment by fastlorisstudios** [comment]
Cool, looks like we're almost there.
If you go into OnlineSubsystemEOS/Source/ThirdParty/EOSSDK then you should see a file called AddSDKFoldersHere.txt. Extract/copy the Bin, Include and Lib folders from the SDK into that folder. Then go back to the EOSBase.uproject, right click "Generate Visual Studio Project Files." Open/reopen the EOSBasic.sln, hit F7 and that should be it.

**Comment by Budgo** [comment]
![image](https://user-images.githubusercontent.com/43380405/88330253-218c7e80-ccf9-11ea-9fd7-901cbe11366b.png)
Hm, I don't see it.

**Comment by fastlorisstudios** [comment]
If your download from the repo has been successful, it should just be here:
https://github.com/gaslightgames/UE4_EOS_Plugin/tree/master/EOSBasic/Plugins/OnlineSubsystemEOS/Source/ThirdParty/EOSSDK

**Comment by Budgo** [comment]
Still no dice. I think at this point I should send over a copy of my files to show what I have, here you are:
https://drive.google.com/file/d/1M7MKlJ8EfE2zTxYBM7firjIb2XUoSJuy/view?usp=sharing

**Comment by Budgo** [comment]
Alright, I decided to scrap this installation and just re-clone the repo, and it works fine now. Sorry for wasting your time!

Also, thanks for your effort in trying to make programming better. I always appreciate programmers who make things, but the people who make the libraries and plugins make it all possible. So thanks!
