### ISSUE TITLE
So, What Do I Do?

### ISSUE THREAD

**Issue by Budgo** [gaslightgames/UE4_EOS_Plugin#35]
Hey. Me again.

I've been poking around the editor for content on the plugin, and I've been poking around Google for how plugins work, but I still have no idea what the default project actually does. No keys seem to work, and the only change I've found that does anything is linking up the parts in the Character Blueprint to make the widgets display. 

What am I missing?!

**Comment by Sessional** [comment]
The sample project requires you to update some values in DefaultEngine.ini and then allows you to log in to the Epic Online Services using the developer tool. It also does not work well when playing in viewport, you are better of switching to the "Standalone Game" setting.

**Comment by fastlorisstudios** [comment]
You need to read up on Epic Online Services, have yourself an account in there and have access to the "Dashboard." Then create a project, client, IDs etc.
In the text on the front page of this project, there are details about what you need (ProductId, SandboxId, DeploymentId etc) and where to put them. Once you have the Dashboard access, you can find these easy enough. And if you open the DefaultEngine.ini in the sample project, you'll see these sections ready, just empty.

After that, you'll need to read up using the Auth Tool, as that's the only thing I'm currently using to test connections. Also, all of the logging goes to the Log files and Output window, not to the screen.
