### ISSUE TITLE
Update to SDK 1.9 and UE4.25.4

### ISSUE THREAD

**Issue by JaZer0** [gaslightgames/UE4_EOS_Plugin#38]
Hi,

first and foremost thanks for making this plugin. Keep going 👍 

I would like to ask if it's possible to update the plugin to be compatible with **UE4.25.4** and **SDK 1.9**?
I just came across your plugin and I don't have the older Versions.

I actually tried building the project just like you described it, but it didn't work.

- First, this comes up:

![grafik](https://user-images.githubusercontent.com/52222760/98378021-ca12e400-2045-11eb-9ada-c5c0e95b0ee4.png)

- and if I say yes this comes up:

![grafik](https://user-images.githubusercontent.com/52222760/98378219-07777180-2046-11eb-82ca-d0567fcb29e3.png)

Is there a way around this problem or do I have to wait for your update?

kind regards,

JaZer0

**Comment by fastlorisstudios** [comment]
Minor updates, like those between 4.25.3 and 4.25.4 will work without a problem, as nothing has been deprecated in the Engine.
Two things.
First, I'm working on the 1.9 update, shouldn't be too much longer.
Second, I'm not certain whether attempting to build via launching the Editor and have it try to auto-compile will work. You will need to manually compile via Visual Studio.

**Comment by fastlorisstudios** [comment]
Fixed and confirmed working in bfa4c4cfd1c7615bb109a14921c204bd3c753591.
