### ISSUE TITLE
Crash when you call EndMetricsSession without having initialized Metrics beforehand

### ISSUE THREAD

**Issue by HiIAmMoot** [gaslightgames/UE4_EOS_Plugin#7]
In my gamecode I simply have it always call EndMetricsSession when shutting down, but this will result in a crash if for some reason the Metrics interface fails to initialize.

**Comment by fastlorisstudios** [comment]
Do you have any more details on this one?
The crash output from Unreal?  Or a log file with the crash?

I'm _guessing_ it's somehow getting passed ln118 in Metrics.cpp, where there's a check for a valid MetricsHandle?

**Comment by fastlorisstudios** [comment]
I've not heard back from you in a while and cannot replicate, so closing. Will re-open if the issue comes back.
